version: "3"
services:
  react-app:
    image: levelupworks-dev
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - levelupworks-network
  api-server:
    image: levelupworks-api
    ports:
      - "6969:6969"
    networks:
      - levelupworks-network
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "8080:8080"
    networks:
      - levelupworks-network
    volumes:
      - mongo-data:/data/db
networks:
  levelupworks-network:
    driver: bridge
volumes:
  mongo-data:
    driver: local
